DROP VIEW IF EXISTS simple_view
GO
CREATE VIEW simple_view AS
SELECT TRADE.*, COUNTERPARTY.COUNTERPARTY_SHORT_NAME, COUNTERPARTY.COUNTERPARTY_FULL_NAME
FROM TRADE
INNER JOIN COUNTERPARTY ON [COUNTERPARTY].[COUNTERPARTY_ID] = [TRADE].[COUNTERPARTY_ID]